# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o6RE9CUUrUDcq5pjVbcB1md7QgMPFZGB
"""

print("Hello, World!")