# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19pckcjYn0IWrm31Jk3BFoDuBWDcPtT_M
"""

#!/bin/python3

import math
import os
import random
import re
import sys

n = int(input().strip())
if (n % 2) == 0:
   print("Not Weird".format(n))
else:
   print("Weird".format(n))