# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pPMvwhrrZ0ROW_iwsYMvU6nVTU1fKwGG
"""

a = int(input(3))
b = int(input(2))
add = int(a) + int(b)
print(add)
subtract = int(a) - int(b)
print(subtract)
multiply = int(a) * int(b)
print(multiply)