# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/109xXIEPbCuwLz6ctiUueje0MYX572J1Z
"""

a = int(input(4))
b = int(input(3))
div = int (a) // int (b)
print(div)
div = float (a) / float (b)
print(div)