# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ytZc8piiQm_JAUGw5l81UhhYmNTpHpPA
"""

n = [0, 1, 2]
loop = [number ** 2 for number in n]
print(loop)