# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RlwGsWlqXJhb9LxUEENQlzwrsWO9fMsU
"""

def is_leap(year):
    leap = False
    
 if (year%4 == 0 and year%100 != 0) or (year%400 == 0) :
    print( year, "True")
else:
    print( year, "False")

year = int(input())
print(is_leap(year))