# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wYinxI7f3X24lB1W-NYkmzaZ7UWF9v76
"""

value=int(input())
for n in range(value) :
    print(n+1, end="")